name: cine_favorite
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  auto_route: ^8.1.3
  skeletonizer: ^1.1.2+1
  dartz: ^0.10.1
  intl: ^0.19.0
  flutter_localization: ^0.2.0
  lottie: ^3.1.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  dio: ^5.4.3+1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/
#Generate freezed models & autoroute file
#flutter pub run build_runner build --delete-conflicting-outputs
